application/models/blog.py
from application.extensions import db
from enum import unique

class BlogModel(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    category_id = db.Column(db.Integer, db.ForeignKey('category_master.category_id'), nullable=False)
    blog_user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    blog_text = db.Column(db.Text, nullable=False)
    blog_creation_date = db.Column(db.DateTime)
    blog_read_count = db.Column(db.Integer, default=0)
    blog_rating_count = db.Column(db.Integer, default=0)
    
class CategoryMaster(db.Model):
    category_id = db.Column(db.Integer, primary_key=True)
    category_name = db.Column(db.String, nullable=False, unique=True)
    blogmodel = db.relationship('BlogModel', backref='categorymaster', lazy=True)
    
class BlogComment(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    blog_id = db.Column(db.Integer, db.ForeignKey('blog_model.id'), nullable=True)
    blog_comment = db.Column(db.Text)
    comment_user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=True)
    blog_rating = db.Column(db.Integer)
    blog_comment_date = db.Column(db.DateTime)

application/models/user.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from enum import unique
from application.extensions import db , login_manager
import datetime


class UserModel(UserMixin, db.Model):
    __tablename__ = 'users'
    
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(100), unique=True)
    username = db.Column(db.String(100))
    password_hash = db.Column(db.String(250))
    registered_on = db.Column(db.DateTime, nullable=False)
    admin = db.Column(db.Boolean, nullable=False, default=False)
    confirmed = db.Column(db.Boolean, nullable=False, default=False)
    confirmed_on = db.Column(db.DateTime, nullable=True)
    
    def __init__(self, email, username, password, confirmed, admin=False, confirmed_on=None):
        self.email = email
        self.username = username
        self.password = self.set_password(password)
        self.registered_on = datetime.datetime.now()
        self.admin = admin
        self.confirmed = confirmed
        self.confirmed_on = confirmed_on
    
    def set_password(self, password):
        self.password_hash = generate_password_hash(password)
        
    def check_password(self, password):
        return check_password_hash(self.password_hash, password)
    
    def check_confirmed(self):
        return self.confirmed
    
    def set_confirmed(self, confirmed=True):
        self.confirmed= confirmed
    
@login_manager.user_loader
def load_user(id):
    return UserModel.query.get(int(id))

project/models/user.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from enum import unique
from project.extensions import db , login_manager
import datetime


class UserModel(UserMixin, db.Model):
    __tablename__ = 'users'
    
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(100), unique=True)
    username = db.Column(db.String(100))
    password_hash = db.Column(db.String(250))
    registered_on = db.Column(db.DateTime, nullable=False)
    admin = db.Column(db.Boolean, nullable=False, default=False)
    confirmed = db.Column(db.Boolean, nullable=False, default=False)
    confirmed_on = db.Column(db.DateTime, nullable=True)
    
    def __init__(self, email, username, password, confirmed, admin=False, confirmed_on=None):
        self.email = email
        self.username = username
        self.password = self.set_password(password)
        self.registered_on = datetime.datetime.now()
        self.admin = admin
        self.confirmed = confirmed
        self.confirmed_on = confirmed_on
    
    def set_password(self, password):
        self.password_hash = generate_password_hash(password)
        
    def check_password(self, password):
        return check_password_hash(self.password_hash, password)
    
    def check_confirmed(self):
        return self.confirmed
    
    def set_confirmed(self, confirmed=True):
        self.confirmed= confirmed
    
@login_manager.user_loader
def load_user(id):
    return UserModel.query.get(int(id))

application/__init__.py
from dotenv import load_dotenv

from flask import Flask
from config import DevelopmentConfig

from application.routes.main import bp as main_bp
from application.routes.users import bp as users_bp
from application.routes.blogs import bp as blogs_bp
from application.extensions import db, login_manager, mail
from application.models.blog import CategoryMaster

from application.routes.blogs.routes import get_all_categories

from flask import Flask, render_template, url_for, redirect, request, flash
from flask_login import login_required, current_user, login_user, logout_user

load_dotenv()

def create_app(config_class=DevelopmentConfig):
    """Application-Factory pattern

    Args:
        config_class (Config): Config 
    """
    # Create flask instance
    app = Flask(__name__)
    app.secret_key = 'zjHUlXmuO85d2LOHqbzpd8_Qvv0XhUYxDr0ZRg2UG04'
    app.config.from_object(config_class)
    
    # extensions
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    
    login_manager.login_view = 'users.login'
    
    # Register blueprints here
    app.register_blueprint(main_bp)
    app.register_blueprint(users_bp)
    app.register_blueprint(blogs_bp)

    # push context manually to app
    with app.app_context():
        db.create_all()  # Handling prerequisite of creating all tables 
        get_all_categories()
    
    @app.route('/test/')
    def test_page():
        return '<h1>Testing the Flask Application Factory Pattern</h1>'

    return app

application/routes/blogs/__init__.py
from flask import Blueprint

bp = Blueprint('blogs', __name__)

from application.routes.blogs import routes

application/routes/blogs/routes.py
from datetime import datetime

from flask import Flask, render_template, url_for, redirect, request, flash
from flask_login import login_required, current_user, login_user, logout_user
from sqlalchemy import func

from application.extensions import db

from application.routes.blogs import bp

from application.models.user import UserModel
from application.models.blog import BlogModel, CategoryMaster, BlogComment


# Global variable
global_all_category_num = None
global_all_category_name = None

def get_all_categories():
    global global_all_category_num, global_all_category_name
    all_category_info = db.session.query(CategoryMaster.category_id, CategoryMaster.category_name)
    all_category_info = list(all_category_info)

    global_all_category_num, global_all_category_name = zip(*all_category_info)


@bp.route("/blogs")
def blogs():
    # if current_user.is_authenticated and current_user.confirmed:
    #     return render_template("blogs/view_blog.html")
    return redirect(url_for('blogs.list_all_blogs'))

@bp.route("/createBlog", methods=['GET', 'POST'])
@login_required
def create_blog():
    if request.method == 'POST':
        category_id = request.form.get("category_id")
        blog_text = request.form.get("blog_text")
        today = datetime.now()
        blog_user_id = current_user.id
        blog_read_count = 0
        blog_rating_count = 0
        
        newBlog = BlogModel(category_id=category_id,
                            blog_user_id=blog_user_id,
                            blog_text=blog_text,
                            blog_creation_date=today,
                            blog_read_count=blog_read_count,
                            blog_rating_count=blog_rating_count)
        
        db.session.add(newBlog)
        db.session.commit()
        return redirect("blogs")
    else:
        return render_template("blogs/create_blog.html", all_category_id=global_all_category_num, all_category_name=global_all_category_name)
    
@bp.route("/viewBlog")
@login_required
def view_blogs():
    all_self_blogs = BlogModel.query.filter(BlogModel.blog_user_id == current_user.id).all()
    return render_template("blogs/view_blog.html", all_self_blogs=all_self_blogs, all_categories=global_all_category_name)

@bp.route("/self_blog_detail/<int:blog_model_id>/<string:blog_model_category>", methods=["GET", "POST"])
@login_required
def self_blog_detail(blog_model_id, blog_model_category):
    blog_model = BlogModel.query.get(blog_model_id)
    if request.method == "POST":
        if request.form['action'] == 'Update':
            blog_model.blog_text = request.form.get('blog_text')
        elif request.form['action'] == 'Delete':
            BlogModel.query.filter_by(id=blog_model_id).delete()
        db.session.commit()
        return redirect('/viewBlog')
    return render_template("blogs/self_blog_detail.html", blog_text=blog_model.blog_text)

@bp.route("/listAllBlogs")
def list_all_blogs():
    all_blogs = BlogModel.query.all()
    all_users = UserModel.query.all()
    return render_template('blogs/list_all_blogs.html', all_blogs=all_blogs, all_users=all_users, all_categories=global_all_category_name)

@bp.route('/blogDetail/<int:blog_model_id>/<string:username>/<string:blog_model_category>', methods=["GET", "POST"])
@login_required
def blog_detail(blog_model_id, username, blog_model_category):
    blog_model = BlogModel.query.get(blog_model_id)
    
    if request.method == 'GET':
        if current_user.id != blog_model.blog_user_id:
            blog_model.blog_read_count += 1
            db.session.commit()
        rating = db.session.query(func.avg(BlogComment.blog_rating)).filter(BlogComment.blog_id == int(blog_model_id)).first()[0]
        return render_template('blogs/blog_detail.html', blog=blog_model, rating=rating, author=username, category=blog_model_category)
    else:
        rate = request.form.get('rating')
        comment = request.form.get('comment')
        blog_id = request.form.get('blog_id')
        print("Comment: ", comment)
        
        old_comment = BlogComment.query.filter(BlogComment.blog_id == blog_model_id).filter(BlogComment.comment_user_id == current_user.id).first()
        print("Old Comment: ", old_comment.blog_comment)
        today = datetime.now()
        
        if old_comment is None:
            blog_model.blog_rating_count += 1
            
            new_comment = BlogComment(
                blog_id=blog_model_id,
                comment_user_id=current_user.id,
                blog_comment=comment,
                blog_rating=rate,
                blog_comment_date=today)
            db.session.add(new_comment)
        else:
            old_comment.blog_comment = comment
            old_comment.blog_rating = rate
        db.session.commit()
        return redirect('/blogs')

application/routes/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from application.routes.main import routes

application/routes/main/routes.py
from flask import render_template
from application.routes.main import bp

@bp.route("/")
def index():
    return render_template('/users/login.html')

application/routes/users/__init__.py
from flask import Blueprint

bp = Blueprint('users', __name__)

from project.routes.users import routes

application/routes/users/routes.py
from datetime import datetime

from flask import Flask, render_template, url_for, redirect, request, flash
from flask_login import login_required, current_user, login_user, logout_user

from project.extensions import db

from project.routes.users import bp
from project.models.user import UserModel

from project.token import generate_confirmation_token, confirm_token
from project.email import send_email


@bp.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated and current_user.confirmed:
        return redirect(url_for('blogs.list_all_blogs'))
    if request.method == 'POST':
        email = request.form.get('email')
        username = request.form.get('username')
        password = request.form.get('password')
        if UserModel.query.filter_by(email=email).first():
            flash('Email Already Registered!', 'success')
            return redirect("unconfirmed")

        user = UserModel(email=email,
                        username=username, 
                        password=password,
                        confirmed=False)
        
        db.session.add(user)
        db.session.commit()
        
        # Generate verification token and send email to user
        token = generate_confirmation_token(user.email)
        confirm_url = url_for('users.confirm_email', token=token, _external=True)
        html = render_template('users/activate.html', confirm_url=confirm_url)
        subject = "Please confirm your email"
        send_email(user.email, subject, html)
        flash("Confirmation link has been sent to the registered email. Kindly confirm it!", 'success')
        return redirect("unconfirmed")
    
    return render_template("users/register.html")

@bp.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated and current_user.confirmed:
        return redirect(url_for('blogs.list_all_blogs'))
    if request.method == 'POST':
        email = request.form.get("email")
        password = request.form.get("password")
        user = UserModel.query.filter_by(email=email).first()
        if user is not None and user.check_password(password=password):
            login_user(user)
            flash('Welcome.', 'success')
            return redirect('unconfirmed')
        return redirect("register")
    return render_template("users/login.html")

@bp.route("/logout")
def logout():
    logout_user()
    return redirect('login')

@bp.route('/confirm/<token>')
@login_required
def confirm_email(token):
    try:
        email = confirm_token(token)
    except:
        flash('The confirmation link is invalid or has expired.', 'danger')
    user = UserModel.query.filter_by(email=email).first_or_404()
    
    if user.confirmed:
        flash('Account already confirmed. Please login.', 'success')
    else:
        user.confirmed = True
        user.confirmed_on = datetime.now()
        db.session.add(user)
        db.session.commit()
        flash('You have confirmed your account. Thanks!', 'success')
    return redirect(url_for('blogs.blogs'))

@bp.route('/unconfirmed')
@login_required
def unconfirmed():
    if current_user.confirmed:
        return redirect(url_for('blogs.list_all_blogs'))
    flash('Please confirm your account!', 'warning')
    return render_template('users/unconfirmed.html')


@bp.route('/resend')
@login_required
def resend_confirmation():
    token = generate_confirmation_token(current_user.email)
    confirm_url = url_for('users.confirm_email', token=token, _external=True)
    html = render_template('users/activate.html', confirm_url=confirm_url)
    subject = "Please confirm your email"
    send_email(current_user.email, subject, html)
    flash('A new confirmation email has been sent.', 'success')
    return redirect(url_for('users.unconfirmed'))

application/templates/users/activate.html
<p>Welcome! Thanks for signing up. Please follow this link to activate your account:</p>
<p><a href="{{ confirm_url }}">{{ confirm_url }}</a></p>
<br>
<p>Cheers!</p>

application/templates/users/login.html
{% extends 'base.html' %}
{% block content %}
<center>
    <div class="container-fluid" >
        <div class="row">
            <div class="col-md-4 col-sm-4 col-xs-12"></div>
            <div class="col-md-4 col-sm-4 col-xs-12">
                <!-- start form -->
                <form class="form-container" method="POST">
                    <h2 class="text-dark form-container--title">Welcome to MyBlogs</h2>
                    <br/>
                    <br/>
                    <h3 class="text-dark">Sign In</h1>
                    <div class="mb-3">
                        <!-- <label for="exampleInputEmail1" class="form-label">Email</label> -->
                        <input type="email" name="email" value="{{ email }}" class="form-control" id="exampleInputEmail1" placeholder="Email" aria-describedby="emailHelp" required>
                    </div>
                    <div class="mb-3">
                        <!-- <label for="exampleInputPassword1" class="form-label">Password</label> -->
                        <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="Password" required>
                    </div>
                    <button type="submit" class="btn btn-success btn-large">Login</button>
                </form>
                <br>
                <!-- end form -->
                <p class="text-dark signup">Account Not Created? <a href="{{ url_for('users.register') }}">Register</a></p>
                <div>
                    {% for message in get_flashed_messages() %}
                        <div class="alert text-dark">
                        <p>{{ message }}</p>
                        </div>
                    {% endfor %}
                </div>

            </div>
            <div class="col-md-4 col-sm-4 col-xs-12"></div>
        </div>
    </div>   
</center>
<br/>
<br/>
{% endblock %}

application/templates/users/register.html
{%extends 'base.html' %}
{% block content %}
<center>
    <div class="container-fluid" >
        <div class="row">
            <div class="col-md-4 col-sm-4 col-xs-12"></div>
            <div class="col-md-4 col-sm-4 col-xs-12">
                <form class="form-container" method="POST">
                    <h1 class="text-dark">Register</h1>
                    <div class="mb-3">
                        <!-- <label for="exampleInputEmail1" class="form-label">Email</label> -->
                        <input type="email" name="email" class="form-control" id="exampleInputEmail1" placeholder="Email" aria-describedby="emailHelp" required>
                    </div>
                    <div class="mb-3">
                        <!-- <label for="exampleInputEmail1" class="form-label">Email</label> -->
                        <input type="text" name="username" class="form-control" placeholder="Username" required>
                    </div>
                    <div class="mb-3">
                        <!-- <label for="exampleInputPassword1" class="form-label">Password</label> -->
                        <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="Password" required>
                    </div>
                    <button type="submit" class="btn btn-success btn-large">Register</button>
                </form>
                <br>
                <p class="text-dark signup">Already registered? <a href="{{ url_for('users.login') }}">Log In</a></p>
                <div>
                    {% for message in get_flashed_messages() %}
                        <div class="alert text-dark">
                        <p>{{ message }}</p>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="col-md-4 col-sm-4 col-xs-12"></div>
        </div>
    </div>
</center>
{% endblock %}

application/templates/users/unconfirmed.html
{% extends "layout.html" %}

{% block content %}

<h1>Welcome!</h1>
<br>
<p>You have not confirmed your account. Please check your inbox (and your spam folder) - you should have received an email with a confirmation link.</p>
<p>Didn't get the email? <a href="{{ url_for('users.resend_confirmation') }}">Resend</a>.</p>

<p><a href="{{ url_for('users.login')}}">Try Login again!</a></h3>

{% endblock %}